spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

app:
  jwtSecret: mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
  jwtExpirationMs: 3000000

project:
  image: images/

server:
  port: 8081
